### ISSUE TITLE
Add alex as a Github Action for PRs that change text

### ISSUE THREAD

**Issue by wuz** [tatianamac/selfdefined#153]
The [alex](https://alexjs.com/) project is a great way to check language for inconsiderate words, which I think fits really well with the ideas of this repo.

I think we could implement this as a Github Action for new PRs, which would run the check against new content changes to definitions.

I'd love to work on this if it's something that makes sense to add!

**Comment by tatianamac** [comment]
Hi, @wuz ! I'd love if you read through this thread first:

https://twitter.com/tesseralis/status/1260421410192650241?s=20

**Comment by wuz** [comment]
Oh wow, yeah that's a really good thread. Thank you so much for sharing @tatianamac! I have used Alex for personal writing in the past without running into that (definitely because I am a white man, which means I don't have to refer to myself with what Alex thinks are "profane" labels)

Thanks for sharing that thread. I think there might be some good work to be done on this project with Github Actions, to help make the task of moderation easier, but this definitely doesn't seem like the right path.

Gonna close this and think a bit on how else we can leverage actions in the future!

**Comment by tatianamac** [comment]
No worries! I definitely think there's potential. I think that the key aspects are ensuring that the linter can be by default set as non-blocking, and also ensuring that education is the first desire. Whenever people perceive things as being totalitarian, they will shut down. This is ofc disappointing, but I suppose my personal quest is to be informative and educational, allowing people the choice to being more thoughtful humans rather than forcing them.
