### ISSUE TITLE
Word suggestion: womxn?

### ISSUE THREAD

**Issue by alexwlchan** [tatianamac/selfdefined#21]
I don't think I could write a definition for it, but it's a word I've seen used more frequently in the last year or so. (It's not a word I use myself, and I don't yet have a good grasp on how it's used. Geez, if only there was a dictionary of words or something…)

Do you think it's appropriate here?

**Comment by tatianamac** [comment]
Yes, absolutely! Adn I know what oyu mean, so often I think "I wish I had a dictionary that...oh, that's why I'm doing this 😅 

Could you please make a pull request and add it as a word in the list? I'll add it to my queue of words to define? (If you're not able/don't know how, that's okay! Here to help!)
