### ISSUE TITLE
✍️ Add 'excerpt' to all words

### ISSUE THREAD

**Issue by tatianamac** [tatianamac/selfdefined#224]
## Current Situation
Thanks to a new PR (#182), social/search engine previews now include an excerpt of the definition. However as this is a new feature, many of the defined terms do not have an excertps

## Desired Situation
All terms to have 'excerpt' included and written.

To check a term's current preview excerpt, in your favourite search engine, paste the URL of the term into the search field. 

To claim a new term, respond with a comment below to let us know you're working on it, and link this issue to the pull request you make. If you're not familiar with GitHub, we can help if you just want to do the writing, you can submit an issue or respond with a comment!

## Checklist
- [ ] ok hand
- [x] ableism
- [ ] Asian-American
- [ ] East Asian
- [ ] South Asian
- [ ] Southeast Asian
- [x] barbaric
- [ ] bierasure
- [ ] biromantic
- [ ] bisexual
- [ ] cisgender
- [ ] crazy
- [ ] derpy
- [ ] digital Blackface
- [ ] dude
- [ ] dumb
- [ ] English as Second Language
- [ ] fatphobia
- [ ] Gaslighting
- [ ] gender pronouns
- [ ] Hispanic
- [ ] hysterical
- [ ] Latin American/Latino/Latina
- [ ] Latinx
- [ ] mansplain
- [ ] minoritised
- [ ] minorities
- [x] -misia
- [ ] neopronouns
- [ ] non-binary
- [ ] Obsessive Compulsive Disorder (OCD)
- [ ] Oriental
- [ ] overrrepresented majority
- [ ] pansexual
- [ ] performative allyship
- [ ] -phobia
- [ ] polyamory
- [ ] pow-wow
- [ ] preferred pronoun
- [ ] pronouns
- [ ] r-word
- [ ] sane
- [ ] sanity check
- [ ] savage
- [ ] spaz
- [ ] suicide
- [ ] tone-deaf
- [ ] transfeminine
- [ ] transgender
- [ ] underrepresented minority
- [ ] unreal
- [ ] white feminism
- [ ] white fragility
- [ ] women and people of colour

**Comment by thejoycekung** [comment]
Hi! I'd like to try helping with this! I don't know if I can do all of these in one PR but I think I can at least do some. I had a question though: Is #227 related to this as well?  

I also noticed in that PR there are excerpts added for `-misia`, `ableism`, and `barbaric`. Does that PR block work on this issue + can we remove those terms from this to-do list?

**Comment by ovlb** [comment]
Hey @thejoycekung, and welcome to Self-Defined!

PR #227 is adding the infrastructure to use the excerpts in social media previews. It does not strictly block writing of them, though. Adding them before #227 is finished will not break anything.

You are right, we can cross the ones already added in the PR off the list. 

Regarding all in one go: That’s definitely no must. In fact, this tracking issue exists so that the work can be done in smaller steps. :)

Looking forward to your contributions! If any questions arise, please don’t hesitate to ask. Also if you'd like, we have a [Slack community](https://selfdefined.slack.com/admin/invites) as well. But joining is totally up to you. We try to have all the important conversations on GitHub.

O*

**Comment by thejoycekung** [comment]
Hi @ovlb, thanks for clarifying! I saw the Slack community being mentioned around other issues/PRs, but I couldn't find any mention of it in the main docs - your invite link seems a little broken though :(

**Comment by tatianamac** [comment]
@thejoycekung It's my fault. I haven't gotten a chance to add it to our documentation. 😭 It's on my long list of things to do, thanks for the reminder!

**Comment by oakthielbar** [comment]
I would like to add some excerpts.

I noticed when reviewing the current excerpts that they reproduce the first line of the definition. Is that the intended format for excerpts? Some of the definitions lead with a line that explains the purely grammatical and linguistic function of a term without any context, and I worry that a direct copy of just the first line could perpetuate the harmful use of some terms.

I also noticed that the excerpt for ableism follows this same format, but in the definition, it is immediately followed by what appears to be an attribution (whereas there is no attribution in the excerpt). Given that the excerpt is displayed in isolation, it is effectively claiming the original words of another author. I believe that this specific situation needs to be addressed with some urgency since this excerpt is currently visible in search results. Should I make a separate issue to track that?

**Comment by tatianamac** [comment]
@oakthielbar I regret that I didn't see your notes here. Would you be willing/able to open this as a new issue (you can even copy over what you wrote here), so we I can address specifics in a fresh issue and PR? Apologies for the extra work. 💙

**Comment by oakthielbar** [comment]
@tatianamac Sounds good to me! It's not much extra work. ❤️
