### ISSUE TITLE
Suggestion: spiritual bypassing

### ISSUE THREAD

**Issue by ericwbailey** [tatianamac/selfdefined#269]
As per John Welwood, by way of [Psychology Today](https://www.psychologytoday.com/us/blog/the-empowerment-diary/201901/what-is-spiritual-bypassing): “using ‘spiritual ideas and practices’ to sidestep personal, emotional ‘unfinished business,’ to shore up a shaky sense of self, or to belittle basic needs, feelings, and developmental tasks.”

In addition to concerns around emotional labor, there is an angle of co-opting the language, beliefs, and practices of India. There are also considerations for downplaying BIPOC concerns and criticism via pushing for "good vibes only."

I could take a shot at writing an initial term, but I feel it would need review from someone with more familiarity with Indian culture and Hindu faith.

**Comment by tatianamac** [comment]
@ericwbailey If you'd like to ghostwrite it, we can check in our review to make sure it's sensitivity-read!

**Comment by jeevajay** [comment]
Hi @ericwbailey, sorry it took me a few days to get to this. I was focusing on some other issues. I reviewed the #292 and as someone with experience of being on the receiving end of toxicity this creates, I'm affirmative of your definition and how Indian Culture and Hinduism predominantly contribute to it.

But, when setting my experience aside, I'm not sure whether this would educate or it would harm the feelings of minoritized people who can't escape from the settings of culture and religion due to society's makings. I've some suggestions but need some time to process it. I will get back to this before the end of the day(IST).

**Comment by ericwbailey** [comment]
Thank you for the review, and for the crit, @jeevajay. Please, take all the time you need.

**Comment by jeevajay** [comment]
I have added my thoughts on #292
