### ISSUE TITLE
🎨 Fix overflowing headline

### ISSUE THREAD

**Issue by tatianamac** [tatianamac/selfdefined#27]
Headline overflows at below settings.

[<img width="572" alt="Screenshot of browser widths, linked." src="https://user-images.githubusercontent.com/7484549/68420770-e984e180-0151-11ea-9371-06ef806b2903.png">](https://mybrowser.fyi/report/5dc4625ac9614f0015298b92)

![Overflow issue](https://user-images.githubusercontent.com/7484549/68422319-d293be80-0154-11ea-8f71-9dc7872e674f.jpg)

**Comment by Klutch27** [comment]
I have an initial solution, setting the word-wrap property to break-word. However, instead of overlapping, it breaks the word at the D. So instead of overlapping, depending on size of viewport, you'll see the following:

<img width="636" alt="Screen Shot 2019-11-21 at 11 35 35 AM" src="https://user-images.githubusercontent.com/49660740/69357425-12799c00-0c53-11ea-8e22-69760250c0d8.png">


Thoughts on this solution? How would you prefer it to break?

**Comment by tatianamac** [comment]
Thanks for your contribution, @Klutch27 !

Breaking by word would be a good idea for instances where the words are aesthetic only (say, we wanted to have `abcdef...wxyz...` as a visual thing and wanted it to break accordingly. However, since this is a word, an an important one (as it's the title), we should probably try to rely on responsive fonts.

I'd propose investigation a solution that involves fluid typography, something with viewport width coming into account:
https://css-tricks.com/snippets/css/fluid-typography/ 

Excited to hear what you come up with!

**Comment by Shimmoril** [comment]
Another data point for the header overflow: 
![image](https://user-images.githubusercontent.com/45545594/69733378-dc289a80-10f2-11ea-998f-daf3fcf8446b.png)

![image](https://user-images.githubusercontent.com/45545594/69733422-ec407a00-10f2-11ea-8052-9e18418f0d5c.png)
Specific version is 70.0.1.

**Comment by tatianamac** [comment]
Additionally, @Klutch27 , here is another resource!

https://codepen.io/MadeByMike/pen/YPJJYv

**Comment by laurakalbag** [comment]
I wonder if using `vw` rather than `vh` for the font-size unit might give you greater ability to calculate according to the width of the columns?

I’m curious to know the design intention here, to work out how we can do it justice in code. Is it to have as big and impactful a header as possible, which splits across two lines if necessary, but is still sympathetic to a small viewport?

**Comment by tatianamac** [comment]
Your read on the design intention is 100% correct! When the luxury of it spanning 2 columns is possible, I'd like it to do that; but when not (narrower viewports), I'd like it to be impactful but not offensively so.

**Comment by laurakalbag** [comment]
I felt a bit bad for hogging the only good first issue, so I opened another issue that might be a candidate for good first issue: #41.

**Comment by codeAbul** [comment]
@tatianamac is anyone currently working on this? If not , I can work on creating a more fluid typographic scale

**Comment by tatianamac** [comment]
You're welcome to—sometimes for first issues it's nice to invite first-time contributors since contributing to OSS can be intimidating. If you wanted to help @Klutch27 with it, that'd be awesome!

**Comment by codeAbul** [comment]
Yes of course. Hi @Klutch27 please feel free to message me if you need someone to work out your solution with. I'd be happy to. Cheers

**Comment by tatianamac** [comment]
Also I think I may need to close this issue as @laurakalbag may have worked it out already with #40.

I'll open a new ticket to develop a more fluid type system and tag you both, @codeAbul and @Klutch27.
